import { Inter, Prompt } from "next/font/google";
import "./globals.css";
import { useLocale, useTranslations } from "next-intl";
import { notFound } from "next/navigation";
import Header from "../components/Header";
import Footer from "../components/Footer";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "SC ZNOJMO FK",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {
  const locale = useLocale();
  if (params.locale !== locale) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
